# Generated by Django 4.2.1 on 2023-05-09 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)])),
            ],
        ),
    ]
