# Generated by Django 4.2.1 on 2023-05-09 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_parkingspacefloormodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='parking',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.parkingmodel'),
        ),
    ]
