# Generated by Django 4.2.1 on 2023-05-09 13:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofilemodel_parking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpaceRowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.parkingspacefloormodel')),
            ],
        ),
    ]
