# Generated by Django 4.2.1 on 2023-05-09 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_parkingspacenumbermodel_delete_parkingspacenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspacefloormodel',
            name='parking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='app.parkingmodel'),
        ),
        migrations.AlterField(
            model_name='parkingspacerowmodel',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='app.parkingspacefloormodel'),
        ),
    ]
