# Generated by Django 4.2.1 on 2023-05-09 14:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_parkingspacefloormodel_parking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=25)),
                ('driver_national_code', models.CharField(max_length=10)),
                ('driver_phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='قالب شماره موبایل رعایت نشده است', regex='^[0][9][0-9]*$')])),
                ('parking_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='app.parkingspacenumbermodel')),
            ],
        ),
    ]
